export const ActionTypes = {
  CREATE_TUTORIAL: "CREATE_TUTORIAL",
  RETRIEVE_TUTORIAL: "RETRIEVE_TUTORIAL",
  RETRIEVE_SINGLE_TUTORIAL: "RETRIEVE_SINGLE_TUTORIAL",
  UPDATE_TUTORIAL: "UPDATE_TUTORIAL",
  DELETE_TUTORIAL: "DELETE_TUTORIAL",
  DELETE_ALL_TUTORIAL: "DELETE_ALL_TUTORIAL",
};
